---
version: "3"
networks:
  service-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24

services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      service-network:
        ipv4_address: 172.16.0.9
  kafka-1:
    image: confluentinc/cp-kafka:latest
    ports:
      - 29092:29092
    networks:
      service-network:
        ipv4_address: 172.16.0.10
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  auth-database:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      service-network:
        ipv4_address: 172.16.0.11

  mail-server:
    image: bytemark/smtp
    restart: always
    ports:
      - 025:025
    networks:
      service-network:
        ipv4_address: 172.16.0.12

  email-service:
    build: ./api
    image: template-emailer-service:latest
    ports:
      - 3000:3000
    networks:
      service-network:
        ipv4_address: 172.16.0.13

  user-interface:
    build: ./ui
    image: user-interface:latest
    ports:
      - 080:080
    networks:
      service-network:
        ipv4_address: 172.16.0.14
