---
version: "3"
networks:
  service-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24

services:
  auth-database:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      service-network:
        ipv4_address: 172.16.0.11

  mail-server:
    image: bytemark/smtp
    restart: always
    ports:
      - 025:025
    networks:
      service-network:
        ipv4_address: 172.16.0.2

  email-service:
    build: ./api
    image: template-emailer-service:latest
    ports:
      - 3000:3000
    networks:
      service-network:
        ipv4_address: 172.16.0.3

  user-interface:
    build: ./ui
    image: user-interface:latest
    ports:
      - 080:080
    networks:
      service-network:
        ipv4_address: 172.16.0.4
